{% set name = "bubbletree" %}
{% set version = "1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 65f3f8cdc0f8b715060b5ad2fef0358a4b25c12eecff28c793a6c94c5360ec46

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - bubbletree

about:
  home: "https://github.com/aemann01/bubbleTree"
  license: "GNU General Public (GPL)"
  license_family: LGPL
  license_file:
  summary: "Bubble plot or heatmap ordered by phylogenetic tree"

extra:
  recipe-maintainers:
    - aemann01
