package:
  name: "bubbletree"
  version: "1.0"

source:
  path: .
  git_url: https://github.com/aemann01/bubbleTree

requirements:
  build:
    - python >=3.8
  run:
    - python >=3.8
    - pandas >=1.1.3
    - biopython >=1.79
    - matplotlib >=3.5.1
    - seaborn >=0.11.0

about:
  home: https://github.com/aemann01/bubbleTree
  license: GPL
  license_family: GPL
  license_file: LICENSE
  summary: "Plot a phylogenetic tree against a bubble plot or heatmap"
